### ISSUE TITLE
Accessibility and speed index checks

### ISSUE THREAD

**Issue by tomaszwylezek** [Physalium/S2RouteAssistant#82]
## Description

The ticket is about accessibility and speed index checks based on results from #81

## Acceptance criteria

- We have reports from accessibility and speed index available and based on that we can plan our next work

**Comment by szymonbuniewicz** [comment]
Accessibility test:
https://axe.deque.com/axe-devtools/tests/5e72ef0c-260b-4394-adc4-2e4db77b920c?configNeedsReview=disabled&configBestPractices=enabled&configAccessibilityStandard=wcag21aa

Speed test:
https://pagespeed.web.dev/analysis/https-road-assistant-adamkierat-pl/5wvdboda84?form_factor=desktop
