### ISSUE TITLE
Create a move about the app

### ISSUE THREAD

**Issue by tomaszwylezek** [Physalium/S2RouteAssistant#88]
## Description

The ticket is about to create a movie which shows all the functionalities available in the app.

## Acceptance criteria

- The movie is created and contains all functionalities
- Everyone who took part in it is mentioned

**Comment by damianosiak** [comment]
The video has been recorded and all that remains is to edit it ;)

**Comment by damianosiak** [comment]
Video has been recorded and edited
https://youtu.be/O0kq-eG3h44

**Comment by damianosiak** [comment]
https://github.com/damianosiak/S2RouteAssistant/assets/49518732/eed228d3-ffef-4d04-a1e2-2e55c04abf41
