### ISSUE TITLE
Create a presentation about app

### ISSUE THREAD

**Issue by tomaszwylezek** [Physalium/S2RouteAssistant#89]
## Description

The ticket is about creating a presentation that shows all the functionalities available in the app. (Reusing screenshots from the movie from #88)

## Acceptance criteria

- The presentation is created and contains all functionalities
- Everyone who took part in it is mentioned

**Comment by damianosiak** [comment]
The presentation has been created and contains all functionalities

[_S2RouteAssistant.pptx](https://github.com/damianosiak/S2RouteAssistant/files/13579405/_S2RouteAssistant.pptx)
